### ISSUE TITLE
pyvips.Image.text  parameter spacing  Can't reduce line spacing, only increase line spacing

### ISSUE THREAD

**Issue by donghuikugou** [libvips/pyvips#384] opened 2023-02-16 06:16 UTC
pyvips.Image.text  parameter spacing  Can't reduce line spacing, only increase line spacing

**Comment by kleisauke** [comment] 2023-02-16 09:12
Duplicate of https://github.com/libvips/libvips/issues/3335?

**Comment by jcupitt** [comment] 2023-02-16 09:26
Yes, I think so. @donghuikugou, this feature has been added now, is there a problem?

**Comment by donghuikugou** [comment] 2023-02-16 12:27
you didn't understand me,  What I mean is to adjust the line spacing like  reduce line spacing in a word document.

import pyvips

img = pyvips.Image.text("Hello\nWorld", font="Prompt Bold 60", fontfile="font/Prompt-Bold.ttf", spacing=2)
img.write_to_file("demo1.png")

img = pyvips.Image.text("Hello\nWorld", font="Prompt Bold 60", fontfile="font/Prompt-Bold.ttf", spacing=10)
img.write_to_file("demo2.png")

**The line spacing cannot be set to close to zero**

demo1.png and demo2.png  is same

**Comment by donghuikugou** [comment] 2023-02-16 12:28
> Yes, I think so. @donghuikugou, this feature has been added now, is there a problem?

![74195dcd475b6cba15024ea971720bbe299e3a6d](https://user-images.githubusercontent.com/47808515/219365169-6fb4d48a-ccf0-4199-b139-b77f67bee670.png)

**Comment by jcupitt** [comment] 2023-02-17 09:39
Spacing zero means relative to the 1.0 spacing hinted by the font. Set it negative to push lines closer than that.

```
$ python3
Python 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.text("hello\nworld", dpi=300, spacing=-30)
>>> x.write_to_file("x.png")
>>> 
```

To make:

![x](https://user-images.githubusercontent.com/580843/219608723-e222efa8-d5f1-49b6-8937-6a99c9835202.png)

**Closed by jcupitt** 2023-02-17 09:39 UTC
